#!/usr/bin/perl
# Send the polargraph to a known location.
# This will attempt to iterate to draw straight (not curved) lines,
# but the tinyg doesn't seem to handle it well.
use warnings;
use strict;

# origin is at l1=800 l2=800 
# xy = 600,500 or so
# separation between the two is 1120

my $w = 1120;
my $feed = 10000;
my $step_size = 40;

my $x0 = shift;
my $y0 = shift;

my $x1 = shift;
my $y1 = shift;

unless($x1)
{
	# go straight to the positoin
	goxy($x0,$y0);
} else {
	# iterate from x0,y0 to x1,y1
	my $dx = $x1 - $x0;
	my $dy = $y1 - $y0;
	my $dist = sqrt($dx*$dx+$dy*$dy);

	my $steps = int($dist/$step_size);
	for(my $i = 0 ; $i < $steps ; $i++)
	{
		$x0 += $dx / $steps;
		$y0 += $dy / $steps;
		goxy($x0,$y0);
		#sleep(1);
	}

	goxy($x1,$y1);
}


sub goxy
{
	my $x = shift;
	my $y = shift;
	
	my $l1 = sqrt(($w-$x)*($w-$x) + $y*$y);
	my $l2 = sqrt($x*$x + $y*$y);

	printf STDERR "%.3f %.3f -> %.3f %.3f\n", $x, $y, $l1, $l2;
	printf "G1 X%.3f Y%.3f F%d\n", $l1, $l2, $feed;
}
